Repository Daniel-W-Innes/SYSC4806-Project-Frontend, pull requests merged in 2022-03, with the labels that each got.

#4 Feature/adi erik astrid/2
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/index.js
  src/pages/CreateSurvey/CreateSurvey.js
  src/pages/CreateSurvey/CreateSurveyElements.js
  src/pages/SurveyList/SurveyList.js
  src/pages/SurveyList/SurveyListElements.js
Labels: enhancement

#6 Added README from back-end
  README.md
  documentation/DatabaseSchema_v1.PNG
  documentation/ListOfSurveys.png
  documentation/ModelClassUML_v1.png
  package-lock.json
Labels: documentation

#10 changed surveyId to id
  src/pages/SurveyList/SurveyList.js
Labels: bug

#15 Added Home, SignIn & SignUp pages
  package-lock.json
  package.json
  src/App.js
  src/components/Navbar.js
  src/components/NavbarElements.js
  src/images/green_gradient_2.png
  src/images/survey_logo.png
  src/index.js
  src/pages/CreateSurvey/CreateSurveyElements.js
  src/pages/Home/Home.js
  src/pages/Home/HomeElements.js
  src/pages/Main.js
  src/pages/SignIn/SignIn.js
  src/pages/SignIn/SignInElements.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUpElements.js
  src/pages/SurveyList/SurveyList.js
  src/pages/SurveyList/SurveyListElements.js
Labels: enhancement

#19 Fix create survey
  package-lock.json
  package.json
  src/App.js
  src/pages/CreateSurvey/CreateSurvey.js
  src/pages/CreateSurvey/CreateSurveyElements.js
Labels: bug

#20 Stop deploying PRs
  .github/workflows/gh-pages.yml
Labels: bug
