Repository Daniel-W-Innes/SYSC4806-Project-Frontend, pull requests merged in 2022-04, with the labels that each got.

#30 Fixed SurveyList to allow a button to view results
  src/App.css
  src/App.js
  src/pages/CreateSurvey/CreateSurvey.js
  src/pages/SurveyList/SurveyList.js
  src/pages/SurveyList/SurveyListElements.js
Labels: enhancement

#35 Update to docs
  README.md
  docs/AnswerSurvey.png
  docs/CreateSurvey.png
  docs/DatabaseSchema.PNG
  docs/DatabaseSchema.png
  docs/DisplayResults1.PNG
  docs/DisplayResults2.PNG
  docs/ListOfSurveys.png
  docs/Models.png
  docs/Models.puml
Labels: documentation

#36 Fix gap in numbers for options
  src/pages/CreateSurvey/CreateSurvey.js
Labels: bug
